name: Drop old releases
description: remove old releases of any repo
author: luccas-freitas

branding:
  color: purple
  icon: delete

inputs:
  keep_latest:
    description: how many latest releases to keep
    required: true
  owner:
    description: owner/organization name of the repository
    required: true
  repos:
    description: repositories names separated by commas. Example repo1,repo2,repo3
    required: true
  delete_tags:
    description: whether to delete tags associated to older releases or not
    required: false
  delete_tag_pattern:
    description: part of the tag name. Example, if you want to delete 0.0.1-beta and 0.0.2-beta but not 0.0.1 then set this to just "beta". If not set then it will target all releases.
    required: false

runs:
  using: "node12"
  main: "index.js"
